--- #YAML:1.0
name:               Test-Resub
version:            2.01
abstract:           Lexically scoped monkey patching for testing
author:
    - Belden Lyman <belden@cpan.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Scalar::Util:  0
    Storable:      0
    Test::More:    0
resources:
    bugtracker:  https://github.com/belden/test-resub/issues
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
