# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Test-Resub
version:      1.03
version_from: lib/Test/Resub.pm
installdirs:  site
requires:
    Class::Std:                    0
    Scalar::Util:                  0
    Storable:                      0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
